### ISSUE TITLE
support to limit the search fields 

### ISSUE THREAD

**Issue by nvtin** [SpoonX/aurelia-datatable#101]
Hi guys.
I think we should have one option to define the field we want to enable search on it.
Example the datatable have 5 columns, but we just want to search on 2 fields.
Now, it enable search on all of 5 fields.
Can you guy update the library to support that?
I really want to do it but I can't run this library with mode dev. (use src code instead of dist/amd)

**Comment by RWOverdijk** [comment]
I don't know what you mean. You can provide the searchColumn yourself.

`@bindable searchColumn     = 'name';`

**Comment by nvtin** [comment]
Hi @RWOverdijk Thanks for your support
As I know, searchColumn is the initial search field as default.
But what I mean is how we limit the fields on search dropdown? (I wish I can add an image here)
example: my record have fields: name, text, created_at, updated_at
and search dropdown will include  name, text, created_at, updated_at.
How I set dropdown just include 'name', 'text'?
I hope you can get what I mean. Thanks for your support

**Comment by RWOverdijk** [comment]
@nvtin Taking a look at the code, that's currently not possible. You could just build your own search drop down then and not use ours, or submit a PR. Columns can be objects, which is perfect because the PR is then simple. Just add a searchable property:

```js
const columns = [{property: '', searchable: false}];
```

And then have it default to true [here](https://github.com/SpoonX/aurelia-datatable/blob/master/src/datatable.js#L299):

```js
{searchable: typeof column.searchable === 'boolean' ? column.searchable : true}
```

And in the view just skip the ones you don't want to render, or maybe create a new getter that excludes the columns that aren't searchable.

**Comment by RWOverdijk** [comment]
CC @jeremyvergnas does my solution sound good to you?

**Comment by jeremyvergnas** [comment]
It does 👍

**Comment by nvtin** [comment]
@RWOverdijk  I have made a PR for it https://github.com/SpoonX/aurelia-datatable/pull/102
